# Config file for automatic testing at travis-ci.org

# Containerized builds
sudo: false

language: python

env:
  # Lowest supported version
  - MARSHMALLOW_VERSION="==2.0.0"
  # Latest release
  - MARSHMALLOW_VERSION=""

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

install:
  - travis_retry pip install -U .
  - travis_retry pip install -r dev-requirements.txt
  # Install lowest supported sqlalchemy version
  - travis_retry pip install sqlalchemy==1.1.0b3
  - travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION"
before_script:
  - flake8 .

script: py.test
